name: Build server executable

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1-alpine3.22
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add openssl-dev musl-dev openssl-libs-static

      - name: Build executable
        run: cargo build -r

      - name: Compress debug sections
        run: objcopy --compress-debug-sections target/release/server ./server

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./server
          if-no-files-found: error
          overwrite: true

