name: Run canary tests

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: "Ping index"
        run: curl -f https://alts-alt.online

      - name: "Ping /ping"
        run: curl -f https://alts-alt.online/api/ping

