name: Check code base validity

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rust:1-alpine3.22
    steps:
      - name: Install dependencies
        run: apk add openssl-dev musl-dev openssl-libs-static

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test

  build:
    uses: ./.github/workflows/build.yml

  lint:
    runs-on: ubuntu-latest
    container:
      image: rust:1-alpine3.22
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install environment dependencies
        run: apk add openssl-dev musl-dev openssl-libs-static

      - name: Install toolchain dependencies
        run: rustup component add clippy && rustup component add rustfmt

      - name: Run linter
        run: cargo clippy

      - name: Run formatter
        run: cargo fmt --all --check

