name: Deploy server to host

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout package
        uses: actions/checkout@v4
      - name: Initialize ssh
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.HOST_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_NAME }} > ~/.ssh/known_hosts
      - name: Rebuild and restart server
        run: |
          ssh ${{ secrets.HOST_USERNAME}}@${{ secrets.HOST_NAME }} < scripts/deploy.sh

