name: Run lint check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run linter
        run: cargo clippy --all-targets --all-features
        env:
          RUSTFLAGS: "-Dwarnings"
